import {
  BulkyWasteDisposalImage,
  BuildingMaterialsDisposalImage,
  ElectricalWasteDisposalImage,
} from '@assets'

import {type Report, StatusOption, PriorityOption} from '@types'

const REPORTS: Report[] = [
  {
    id: '1',
    images: [
      BulkyWasteDisposalImage,
      BuildingMaterialsDisposalImage,
      ElectricalWasteDisposalImage,
    ],
    title: 'Bulky waste',
    description:
      'Abandonment of bulky waste on the sidewalk. Urgent removal needed.',
    address: '45 Turin Street',
    location: {
      latitude: 45.4654,
      longitude: 9.1859,
    },
    date: new Date('2025-05-26T14:30:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '2',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Building materials',
    description:
      'Building materials abandoned after renovation work. They occupy part of the road.',
    address: '12 Duomo Square',
    location: {
      latitude: 45.464,
      longitude: 9.19,
    },
    date: new Date('2025-05-25T14:30:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Medium,
  },
  {
    id: '3',
    images: [
      ElectricalWasteDisposalImage,
      BulkyWasteDisposalImage,
      BuildingMaterialsDisposalImage,
    ],
    title: 'Electrical waste',
    description:
      'Abandoned appliances and electronic equipment. Potential environmental risk.',
    address: '8 Montenapoleone Street',
    location: {
      latitude: 45.4685,
      longitude: 9.195,
    },
    date: new Date('2025-05-23T14:30:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Low,
  },
  {
    id: '4',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Abandoned furniture',
    description:
      'Sofa and other furniture abandoned in the public park. They obstruct passage.',
    address: '78 Garibaldi Street',
    location: {
      latitude: 45.4692,
      longitude: 9.1834,
    },
    date: new Date('2025-05-22T10:15:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.Medium,
  },
  {
    id: '5',
    images: [
      ElectricalWasteDisposalImage,
      BulkyWasteDisposalImage,
      BuildingMaterialsDisposalImage,
    ],
    title: 'Computers and monitors',
    description:
      'Several computers and monitors abandoned near the dumpsters. Special collection needed.',
    address: '34 Vittorio Emanuele Course',
    location: {
      latitude: 45.4655,
      longitude: 9.1921,
    },
    date: new Date('2025-05-21T16:45:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '6',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Rubble and bricks',
    description:
      'Piles of rubble and bricks abandoned after demolition. They occupy the sidewalk.',
    address: '56 Dante Street',
    location: {
      latitude: 45.4695,
      longitude: 9.1825,
    },
    date: new Date('2025-05-20T09:30:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '7',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Large appliances',
    description:
      'Refrigerator and washing machine abandoned in the street. They partially block the pedestrian passage.',
    address: '23 Manzoni Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2025-05-19T14:20:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '8',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Batteries and accumulators',
    description:
      'Piles of used batteries and accumulators abandoned. Risk of environmental contamination.',
    address: '5 Republic Square',
    location: {
      latitude: 45.4642,
      longitude: 9.1908,
    },
    date: new Date('2025-05-18T11:10:00'),
    status: StatusOption.Working,
    priority: PriorityOption.High,
  },
  {
    id: '9',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Paints and solvents',
    description:
      'Cans of paint and solvents abandoned. Risk of spillage and pollution.',
    address: '67 Leopardi Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-05-17T15:50:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.High,
  },
  {
    id: '10',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Old mattresses',
    description:
      'Three old mattresses abandoned on the side of the road. Removal needed.',
    address: '89 Magenta Course',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-05-16T13:25:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.Low,
  },
  {
    id: '11',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Electric cables',
    description:
      'Tangle of abandoned electric cables. Potential danger for passersby.',
    address: '12 Brera Street',
    location: {
      latitude: 45.4681,
      longitude: 9.1906,
    },
    date: new Date('2025-05-15T10:40:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Medium,
  },
  {
    id: '12',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken tiles',
    description:
      'Piles of broken tiles abandoned after renovation. Risk of injury.',
    address: '45 Solferino Street',
    location: {
      latitude: 45.469,
      longitude: 9.191,
    },
    date: new Date('2025-05-14T17:15:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '13',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Used tires',
    description:
      'Several used tires abandoned. Risk of water stagnation and mosquito proliferation.',
    address: '78 Certosa Avenue',
    location: {
      latitude: 45.4825,
      longitude: 9.1645,
    },
    date: new Date('2025-05-13T09:05:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.Medium,
  },
  {
    id: '14',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Old refrigerator',
    description:
      'Refrigerator abandoned near the dumpsters. Potential environmental risk.',
    address: '12 Roma Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-05-12T14:30:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '15',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken sofa',
    description: 'Sofa left on the sidewalk, obstructs passage.',
    address: '1 Duomo Square',
    location: {
      latitude: 45.4642,
      longitude: 9.1908,
    },
    date: new Date('2025-05-10T10:00:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Low,
  },
  {
    id: '16',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Cement bags',
    description: 'Hardened cement bags abandoned in a parking lot.',
    address: '22 Turin Street',
    location: {
      latitude: 45.4654,
      longitude: 9.1859,
    },
    date: new Date('2025-05-09T16:45:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.Medium,
  },
  {
    id: '17',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken TV',
    description: 'TV left in a playground.',
    address: '5 Garibaldi Street',
    location: {
      latitude: 45.4692,
      longitude: 9.1834,
    },
    date: new Date('2025-05-08T11:20:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.Low,
  },
  {
    id: '18',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Used mattress',
    description: 'Mattress abandoned near a school.',
    address: '33 Manzoni Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2025-05-07T08:50:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.High,
  },
  {
    id: '19',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Plastic pipes',
    description: 'Plastic pipes abandoned near a construction site.',
    address: '15 Larga Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-05-06T12:30:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '20',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken printer',
    description: 'Printer left next to a bus stop.',
    address: '8 Carducci Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-05-05T09:00:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.Medium,
  },
  {
    id: '21',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Used armchair',
    description: 'Armchair abandoned in a public parking lot.',
    address: '21 Sforza Street',
    location: {
      latitude: 45.4655,
      longitude: 9.1921,
    },
    date: new Date('2025-05-04T18:10:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.High,
  },
  {
    id: '22',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Wooden planks',
    description: 'Wooden planks left near a dumpster.',
    address: '3 Verdi Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-05-03T15:40:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '23',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken microwave',
    description: 'Microwave oven abandoned in a green area.',
    address: '19 Mazzini Street',
    location: {
      latitude: 45.4667,
      longitude: 9.1912,
    },
    date: new Date('2025-05-02T11:25:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '24',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Double bed',
    description: 'Double bed abandoned near a supermarket.',
    address: '7 Fermi Street',
    location: {
      latitude: 45.4663,
      longitude: 9.1909,
    },
    date: new Date('2025-05-01T13:00:00'),
    status: StatusOption.Working,
    priority: PriorityOption.High,
  },
  {
    id: '25',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Old doors',
    description: 'Two wooden doors left next to a construction site.',
    address: '11 Pasteur Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-04-30T17:30:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.Low,
  },
  {
    id: '26',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken air conditioner',
    description: 'Air conditioner abandoned near a school.',
    address: '2 Archimede Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-04-29T10:15:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '27',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Dining table',
    description: 'Dining table left in an underground parking lot.',
    address: '18 Galilei Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-04-28T19:45:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '28',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken window',
    description: 'Glass and wood window abandoned near a park.',
    address: '9 Parini Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-04-27T08:20:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Medium,
  },
  {
    id: '29',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken washing machine',
    description: 'Washing machine abandoned in the courtyard of a condominium.',
    address: '14 Newton Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2025-04-26T12:15:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.High,
  },
  {
    id: '30',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Debris bags',
    description: 'Bags of construction debris left after demolition.',
    address: '6 Edison Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-04-25T14:30:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.Medium,
  },
  {
    id: '31',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken laptop',
    description: 'Laptop abandoned near a library.',
    address: '25 Marconi Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-04-24T16:45:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '32',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Dismantled wardrobe',
    description: 'Wooden wardrobe left on the sidewalk.',
    address: '12 Tesla Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-04-23T09:20:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '33',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Damaged solar panels',
    description: 'Abandoned damaged solar panels.',
    address: '8 Volta Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-04-22T11:10:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '34',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken fan',
    description: 'Ceiling fan abandoned in a garage.',
    address: '19 Curie Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2025-04-21T15:35:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '35',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Used desk',
    description: 'Wooden desk left in a parking lot.',
    address: '4 Fleming Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-04-20T13:25:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '36',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken bricks',
    description: 'Piles of broken bricks after renovation.',
    address: '27 Pasteur Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-04-19T10:40:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '37',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken vacuum cleaner',
    description: 'Vacuum cleaner abandoned near a dumpster.',
    address: '13 Darwin Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-04-18T17:55:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '38',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken chairs',
    description: 'Three broken plastic chairs left in a park.',
    address: '22 Mendel Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2025-03-31T08:30:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '39',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Metal pipes',
    description: 'Abandoned metal pipes after plumbing work.',
    address: '16 Planck Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-03-30T14:15:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '40',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Old radio',
    description: 'Vintage radio abandoned near a bus stop.',
    address: '9 Bohr Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-03-29T11:45:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '41',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Dismantled bookshelf',
    description: 'Wooden bookshelf abandoned in front of a school.',
    address: '7 Heisenberg Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-03-28T16:20:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '42',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Ceramic tiles',
    description: 'Boxes of broken ceramic tiles.',
    address: '11 Schrödinger Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2025-03-27T09:35:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '43',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Landline phone',
    description: 'Old landline phone left in the street.',
    address: '18 Fermi Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-03-26T12:50:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '44',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Single mattress',
    description: 'Single mattress abandoned in an alley.',
    address: '5 Rutherford Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-03-25T15:10:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '45',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Paint buckets',
    description: 'Empty paint buckets left after painting.',
    address: '23 Pauli Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-03-24T10:25:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '46',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Photocopier',
    description: 'Broken photocopier abandoned in an office.',
    address: '15 Dirac Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2025-03-23T13:40:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '47',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Old bedside table',
    description: 'Wooden bedside table left on the sidewalk.',
    address: '8 Hawking Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-03-22T17:15:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '48',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken glass sheets',
    description: 'Broken glass sheets from a window.',
    address: '20 Planck Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-03-21T08:55:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '49',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken DVD player',
    description: 'DVD player abandoned in a park.',
    address: '12 Maxwell Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-03-20T14:30:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '50',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken trash can',
    description: 'Damaged trash can.',
    address: '17 Faraday Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2025-03-19T11:45:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '51',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Thermal insulation',
    description: 'Insulating panels abandoned after work.',
    address: '6 Ampère Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-03-18T16:20:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '52',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken calculator',
    description: 'Damaged electronic calculator.',
    address: '24 Ohm Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-03-17T09:10:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '53',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Garden bench',
    description: 'Rusty iron bench abandoned.',
    address: '13 Hertz Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-03-16T12:35:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '54',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken plasterboard',
    description: 'Pieces of plasterboard after demolition.',
    address: '10 Gauss Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2025-03-15T15:50:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '55',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken portable stereo',
    description: 'Broken portable stereo left in the square.',
    address: '21 Coulomb Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-03-14T10:15:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '56',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Large mirror',
    description: 'Broken bathroom mirror abandoned.',
    address: '7 Joule Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-03-13T13:25:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '57',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Electric cables',
    description: 'Reel of abandoned electric cables.',
    address: '14 Watt Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-03-12T17:40:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '58',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken game console',
    description: 'Video game console with damaged controls.',
    address: '19 Pascal Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2025-03-11T08:50:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '59',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Shopping cart',
    description: 'Abandoned shopping cart in the street.',
    address: '3 Kelvin Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-03-10T14:05:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '60',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken sanitary ware',
    description: 'Toilet and bidet broken after renovation.',
    address: '26 Bernoulli Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-03-09T11:30:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '61',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken coffee machine',
    description: 'Espresso coffee machine broken.',
    address: '9 Torricelli Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-02-28T16:45:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '62',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Small refrigerator',
    description: 'Mini fridge abandoned near a bar.',
    address: '15 Galileo Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2025-02-27T09:20:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '63',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken roof tiles',
    description: 'Roof tiles fallen after a storm.',
    address: '22 Archimede Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-02-26T12:10:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '64',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken doorbell',
    description: 'Damaged electronic doorbell.',
    address: '8 Euclide Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-02-25T15:35:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '65',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken bicycle',
    description: 'Damaged bicycle without wheels.',
    address: '11 Pitagora Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-02-24T10:25:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '66',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Old gutters',
    description: 'Pieces of rusty metal gutter.',
    address: '17 Talete Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2025-02-23T13:40:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '67',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken wifi router',
    description: 'Abandoned internet router.',
    address: '4 Apollonio Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-02-22T17:55:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '68',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken wheelchair',
    description: 'Damaged wheelchair.',
    address: '20 Eratostene Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-02-21T08:15:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '69',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Wooden panels',
    description: 'Plywood panels after demolition.',
    address: '13 Ipparco Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-02-20T14:50:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '70',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken tablet',
    description: 'Tablet with shattered screen.',
    address: '6 Aristarco Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2025-02-19T11:25:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '71',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Used dresser',
    description: 'Wooden dresser with broken drawers.',
    address: '19 Anassagora Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-02-18T16:10:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '72',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Fallen plaster',
    description: 'Pieces of plaster fallen from the facade.',
    address: '25 Democrito Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-02-17T09:35:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '73',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken TV decoder',
    description: 'Digital terrestrial decoder broken.',
    address: '12 Empedocle Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-02-16T12:45:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '74',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken shelves',
    description: 'Wooden shelves fallen from the wall.',
    address: '7 Zenone Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2025-02-15T15:20:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '75',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Concrete blocks',
    description: 'Reinforced concrete blocks after demolition.',
    address: '18 Parmenide Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-02-14T10:55:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '76',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken headphones',
    description: 'Damaged stereo headphones.',
    address: '23 Eraclito Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-02-13T13:30:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '77',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken umbrella',
    description: 'Garden umbrella torn by the wind.',
    address: '9 Leucippo Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-02-12T17:15:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '78',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Asbestos dust',
    description: 'Residues of material containing asbestos.',
    address: '14 Melisso Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2025-02-11T08:40:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '79',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken external hard drive',
    description: 'Damaged external hard drive.',
    address: '21 Gorgia Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-02-10T14:25:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '80',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken stroller',
    description: "Children's stroller with damaged wheels.",
    address: '5 Protagora Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-02-09T11:50:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '81',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Old windows',
    description: 'Aluminum frames replaced.',
    address: '16 Ippia Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-01-31T16:35:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '82',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Damaged mouse and keyboard',
    description: 'Damaged computer peripherals.',
    address: '22 Prodico Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2025-01-30T09:15:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '83',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Torn awning',
    description: 'Awning torn by bad weather.',
    address: '8 Antifonte Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-01-29T12:40:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '84',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Bathroom coverings',
    description: 'Old bathroom tiles removed.',
    address: '11 Liside Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-01-28T15:55:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '85',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken floor lamp',
    description: 'Floor lamp with broken base.',
    address: '17 Crizia Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-01-27T10:20:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '86',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Rusty workbench',
    description: 'Metal workbench rusty.',
    address: '24 Callicle Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2025-01-26T13:45:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '87',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Damaged roof tiles',
    description: 'Roof tiles fallen during work.',
    address: '6 Trasimaco Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-01-25T17:10:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '88',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken alarm clock',
    description: 'Alarm clock with broken display.',
    address: '13 Alcidamante Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-01-24T08:25:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '89',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken coat rack',
    description: 'Wooden coat rack with broken hooks.',
    address: '19 Isocrate Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-01-23T14:50:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '90',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Damaged screed',
    description: 'Pieces of demolished screed.',
    address: '25 Lisia Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2025-01-22T11:15:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '91',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken smartphone',
    description: 'Cell phone with shattered screen.',
    address: '7 Eschine Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-01-21T16:30:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '92',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken stool',
    description: 'Bar stool with broken legs.',
    address: '12 Dinarco Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-01-20T09:45:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '93',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Kerbs',
    description: 'Concrete kerbs removed from the road.',
    address: '18 Iperide Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-01-19T12:20:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '94',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken charger',
    description: 'Damaged mobile phone charger.',
    address: '23 Demostene Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2025-01-18T15:35:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '95',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Old carpet',
    description: 'Persian carpet damaged by humidity.',
    address: '9 Licurgo Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-01-17T10:50:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '96',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Hollow bricks',
    description: 'Hollow bricks for construction abandoned.',
    address: '15 Andocide Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-01-16T13:15:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '97',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken speakers',
    description: 'Audio speakers with damaged cones.',
    address: '21 Antifonte Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-01-15T17:25:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '98',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Flower vase',
    description: 'Terracotta vase broken and fallen from the balcony.',
    address: '4 Crizia Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2024-12-31T08:40:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '99',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Waterproof sheaths',
    description: 'Rolls of worn bituminous sheathing.',
    address: '26 Prodico Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2024-12-30T14:55:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '100',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken webcam',
    description: 'Computer webcam with damaged lens.',
    address: '11 Ippia Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2024-12-29T11:10:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '101',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken garden gate',
    description: 'Garden gate with broken hinges.',
    address: '16 Liside Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2024-12-28T16:20:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '102',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Bathroom tiles',
    description: 'Ceramic coverings removed from the bathroom.',
    address: '8 Callicle Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2024-12-27T09:35:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '103',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken audio mixer',
    description: 'Audio mixer console with broken potentiometers.',
    address: '22 Trasimaco Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2024-12-26T12:45:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '104',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken flower pot',
    description: 'Concrete flower pot with deep cracks.',
    address: '19 Alcidamante Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2024-12-25T15:50:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '105',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Reinforced concrete',
    description: 'Blocks of reinforced concrete from demolition.',
    address: '3 Isocrate Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2024-12-24T10:25:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '106',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken TV remote',
    description: 'Remote control with non-working buttons.',
    address: '14 Lisia Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2024-12-23T13:40:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '107',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken office armchair',
    description: 'Office chair with broken wheels.',
    address: '27 Eschine Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2024-12-22T17:15:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '108',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Rusty flashings',
    description: 'Rusty roof flashings.',
    address: '20 Dinarco Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2024-12-21T08:30:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '109',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken game controller',
    description: 'Game controller with broken analog sticks.',
    address: '5 Iperide Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2024-12-20T14:05:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '110',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken plastic container',
    description: 'Damaged container for waste separation.',
    address: '12 Demostene Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2024-12-19T11:20:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '111',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Rusty fence posts',
    description: 'Iron posts for fencing, rusty.',
    address: '25 Licurgo Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2024-12-18T16:45:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '112',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken internet modem',
    description: 'ADSL modem with broken power supply.',
    address: '7 Andocide Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2024-12-17T09:55:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '113',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken clothes drying rack',
    description: 'Aluminum clothes drying rack bent by the wind.',
    address: '18 Antifonte Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2024-12-16T12:30:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '114',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Abandoned tuff blocks',
    description: 'Blocks of tuff for construction abandoned.',
    address: '21 Crizia Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2024-12-15T15:15:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '115',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Damaged USB flash drive',
    description: 'Damaged USB device.',
    address: '13 Prodico Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2024-12-14T10:40:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '116',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Unstable ironing board',
    description: 'Ironing board with unstable legs.',
    address: '24 Ippia Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2024-12-13T13:25:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '117',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Rusty ventilation grille',
    description: 'Ossified ventilation grilles.',
    address: '10 Liside Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2024-12-12T17:50:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '118',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Damaged ethernet cable',
    description: 'Damaged network cable.',
    address: '16 Callicle Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2024-12-11T08:15:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '119',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken basin',
    description: 'Plastic basin with a punctured bottom.',
    address: '9 Trasimaco Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2024-12-10T14:35:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '120',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Window frame',
    description: 'Aluminum window frame after replacement.',
    address: '23 Alcidamante Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2024-12-09T11:50:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '121',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken power bank',
    description: 'Portable battery that does not recharge.',
    address: '15 Isocrate Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2024-12-08T16:25:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '122',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Wooden chest',
    description: 'Antique chest with a broken lid.',
    address: '6 Lisia Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2024-12-07T09:10:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '123',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken concrete',
    description: 'Pieces of concrete from road demolition.',
    address: '17 Eschine Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2024-12-06T12:40:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '124',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken video camera',
    description: 'Digital video camera with a blocked lens.',
    address: '28 Dinarco Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2024-12-05T15:55:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '125',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Broken trash bin',
    description: 'Trash bin with broken wheels.',
    address: '12 Iperide Street',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2024-12-04T10:20:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '126',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Rusty wire mesh',
    description: 'Rolls of rusty wire mesh.',
    address: '19 Demostene Street',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2024-12-03T13:45:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '127',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Broken switch',
    description: 'Damaged electrical switch.',
    address: '4 Lycurgus Street',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2024-12-02T17:30:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '128',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Step ladder',
    description: 'Aluminum ladder with bent steps.',
    address: '26 Andocides Street',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2024-12-01T08:45:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
]

export default REPORTS
