// Mock user data for leaderboard
export const userData = [
  {id: '1', name: 'Alice Rossi', points: 120, badge: 'Gold'},
  {id: '2', name: 'Bob Bianchi', points: 95, badge: 'Silver'},
  {id: '3', name: 'Carla Verdi', points: 80, badge: 'Bronze'},
  {id: '4', name: 'Dario Neri', points: 60, badge: ''},
  {id: '5', name: 'Elena Blu', points: 40, badge: ''},
]
import {
  BulkyWasteDisposalImage,
  BuildingMaterialsDisposalImage,
  ElectricalWasteDisposalImage,
} from '@assets'

import {type Report, StatusOption, PriorityOption} from '@types'

const REPORTS: Report[] = [
  {
    id: '1',
    images: [
      BulkyWasteDisposalImage,
      BuildingMaterialsDisposalImage,
      ElectricalWasteDisposalImage,
    ],
    title: 'Rifiuti ingombranti',
    description:
      'Abbandono di rifiuti ingombranti sul marciapiede. Necessaria rimozione urgente.',
    address: 'Via Torino 45',
    location: {
      latitude: 45.4654,
      longitude: 9.1859,
    },
    date: new Date('2025-05-26T14:30:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '2',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Materiali edili',
    description:
      'Materiali edili abbandonati dopo lavori di ristrutturazione. Occupano parte della strada.',
    address: 'Piazza Duomo 12',
    location: {
      latitude: 45.464,
      longitude: 9.19,
    },
    date: new Date('2025-05-25T14:30:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Medium,
  },
  {
    id: '3',
    images: [
      ElectricalWasteDisposalImage,
      BulkyWasteDisposalImage,
      BuildingMaterialsDisposalImage,
    ],
    title: 'Rifiuti elettrici',
    description:
      'Elettrodomestici e apparecchiature elettroniche abbandonate. Potenziale rischio ambientale.',
    address: 'Via Montenapoleone 8',
    location: {
      latitude: 45.4685,
      longitude: 9.195,
    },
    date: new Date('2025-05-23T14:30:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Low,
  },
  {
    id: '4',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Mobili abbandonati',
    description:
      'Divano e altri mobili abbandonati nel parco pubblico. Creano ostacolo al passaggio.',
    address: 'Via Garibaldi 78',
    location: {
      latitude: 45.4692,
      longitude: 9.1834,
    },
    date: new Date('2025-05-22T10:15:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.Medium,
  },
  {
    id: '5',
    images: [
      ElectricalWasteDisposalImage,
      BulkyWasteDisposalImage,
      BuildingMaterialsDisposalImage,
    ],
    title: 'Computer e monitor',
    description:
      'Diversi computer e monitor abbandonati vicino ai cassonetti. Necessaria raccolta speciale.',
    address: 'Corso Vittorio Emanuele 34',
    location: {
      latitude: 45.4655,
      longitude: 9.1921,
    },
    date: new Date('2025-05-21T16:45:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '6',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Calcinacci e mattoni',
    description:
      'Cumulo di calcinacci e mattoni abbandonati dopo demolizione. Occupano il marciapiede.',
    address: 'Via Dante 56',
    location: {
      latitude: 45.4695,
      longitude: 9.1825,
    },
    date: new Date('2025-05-20T09:30:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '7',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Elettrodomestici grandi',
    description:
      'Frigorifero e lavatrice abbandonati in strada. Bloccano parzialmente il passaggio pedonale.',
    address: 'Via Manzoni 23',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2025-05-19T14:20:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '8',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Batterie e pile',
    description:
      'Accumulo di batterie e pile usate abbandonate. Rischio di contaminazione ambientale.',
    address: 'Piazza Repubblica 5',
    location: {
      latitude: 45.4642,
      longitude: 9.1908,
    },
    date: new Date('2025-05-18T11:10:00'),
    status: StatusOption.Working,
    priority: PriorityOption.High,
  },
  {
    id: '9',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Vernici e solventi',
    description:
      'Barattoli di vernice e solventi abbandonati. Rischio di sversamento e inquinamento.',
    address: 'Via Leopardi 67',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-05-17T15:50:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.High,
  },
  {
    id: '10',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Materassi vecchi',
    description:
      'Tre materassi vecchi abbandonati sul ciglio della strada. Necessaria rimozione.',
    address: 'Corso Magenta 89',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-05-16T13:25:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.Low,
  },
  {
    id: '11',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Cavi elettrici',
    description:
      'Matassa di cavi elettrici abbandonati. Potenziale pericolo per i passanti.',
    address: 'Via Brera 12',
    location: {
      latitude: 45.4681,
      longitude: 9.1906,
    },
    date: new Date('2025-05-15T10:40:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Medium,
  },
  {
    id: '12',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Piastrelle rotte',
    description:
      'Cumulo di piastrelle rotte abbandonate dopo ristrutturazione. Rischio di ferimento.',
    address: 'Via Solferino 45',
    location: {
      latitude: 45.469,
      longitude: 9.191,
    },
    date: new Date('2025-05-14T17:15:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '13',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Pneumatici usati',
    description:
      'Diversi pneumatici usati abbandonati. Rischio di ristagno acqua e proliferazione zanzare.',
    address: 'Viale Certosa 78',
    location: {
      latitude: 45.4825,
      longitude: 9.1645,
    },
    date: new Date('2025-05-13T09:05:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.Medium,
  },
  {
    id: '14',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Vecchio frigorifero',
    description:
      'Frigorifero abbandonato vicino ai cassonetti. Potenziale rischio ambientale.',
    address: 'Via Roma 12',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-05-12T14:30:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '15',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Divano rotto',
    description: 'Divano lasciato sul marciapiede, ostruisce il passaggio.',
    address: 'Piazza Duomo 1',
    location: {
      latitude: 45.4642,
      longitude: 9.1908,
    },
    date: new Date('2025-05-10T10:00:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Low,
  },
  {
    id: '16',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Sacchi di cemento',
    description: 'Sacchi di cemento indurito abbandonati in un parcheggio.',
    address: 'Via Torino 22',
    location: {
      latitude: 45.4654,
      longitude: 9.1859,
    },
    date: new Date('2025-05-09T16:45:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.Medium,
  },
  {
    id: '17',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Televisore rotto',
    description: 'Televisore lasciato in un parco giochi.',
    address: 'Via Garibaldi 5',
    location: {
      latitude: 45.4692,
      longitude: 9.1834,
    },
    date: new Date('2025-05-08T11:20:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.Low,
  },
  {
    id: '18',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Materasso usato',
    description: 'Materasso abbandonato vicino a una scuola.',
    address: 'Via Manzoni 33',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2025-05-07T08:50:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.High,
  },
  {
    id: '19',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Tubi in plastica',
    description: 'Tubi in plastica abbandonati vicino a un cantiere.',
    address: 'Via Larga 15',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-05-06T12:30:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '20',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Stampante rotta',
    description: 'Stampante lasciata accanto a una fermata dell’autobus.',
    address: 'Via Carducci 8',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-05-05T09:00:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.Medium,
  },
  {
    id: '21',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Poltrona usata',
    description: 'Poltrona abbandonata in un parcheggio pubblico.',
    address: 'Via Sforza 21',
    location: {
      latitude: 45.4655,
      longitude: 9.1921,
    },
    date: new Date('2025-05-04T18:10:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.High,
  },
  {
    id: '22',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Assi di legno',
    description: 'Assi di legno lasciate vicino a un cassonetto.',
    address: 'Via Verdi 3',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-05-03T15:40:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '23',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Microonde rotto',
    description: 'Forno a microonde abbandonato in un’area verde.',
    address: 'Via Mazzini 19',
    location: {
      latitude: 45.4667,
      longitude: 9.1912,
    },
    date: new Date('2025-05-02T11:25:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '24',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Letto matrimoniale',
    description: 'Letto matrimoniale abbandonato vicino a un supermercato.',
    address: 'Via Fermi 7',
    location: {
      latitude: 45.4663,
      longitude: 9.1909,
    },
    date: new Date('2025-05-01T13:00:00'),
    status: StatusOption.Working,
    priority: PriorityOption.High,
  },
  {
    id: '25',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Porte vecchie',
    description: 'Due porte in legno lasciate accanto a un cantiere.',
    address: 'Via Pasteur 11',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-04-30T17:30:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.Low,
  },
  {
    id: '26',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Condizionatore rotto',
    description: 'Condizionatore abbandonato vicino a una scuola.',
    address: 'Via Archimede 2',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-04-29T10:15:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '27',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Tavolo da pranzo',
    description: 'Tavolo da pranzo lasciato in un parcheggio sotterraneo.',
    address: 'Via Galilei 18',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-04-28T19:45:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '28',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Finestra rotta',
    description: 'Finestra in vetro e legno abbandonata vicino a un parco.',
    address: 'Via Parini 9',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-04-27T08:20:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Medium,
  },
  {
    id: '29',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Lavatrice rotta',
    description: 'Lavatrice abbandonata nel cortile di un condominio.',
    address: 'Via Newton 14',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2025-04-26T12:15:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.High,
  },
  {
    id: '30',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Sacchi di detriti',
    description: 'Sacchi di detriti edili lasciati dopo demolizione.',
    address: 'Via Edison 6',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-04-25T14:30:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.Medium,
  },
  {
    id: '31',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Computer portatile',
    description: 'Laptop rotto abbandonato vicino a una biblioteca.',
    address: 'Via Marconi 25',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-04-24T16:45:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '32',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Armadio dismesso',
    description: 'Armadio in legno lasciato sul marciapiede.',
    address: 'Via Tesla 12',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-04-23T09:20:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '33',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Pannelli solari',
    description: 'Pannelli solari danneggiati abbandonati.',
    address: 'Via Volta 8',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-04-22T11:10:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '34',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Ventilatore rotto',
    description: 'Ventilatore da soffitto abbandonato in un garage.',
    address: 'Via Curie 19',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2025-04-21T15:35:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '35',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Scrivania usata',
    description: 'Scrivania in legno lasciata in un parcheggio.',
    address: 'Via Fleming 4',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-04-20T13:25:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '36',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Mattoni rotti',
    description: 'Cumulo di mattoni rotti dopo ristrutturazione.',
    address: 'Via Pasteur 27',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-04-19T10:40:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '37',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Aspirapolvere rotto',
    description: 'Aspirapolvere abbandonato vicino a un cassonetto.',
    address: 'Via Darwin 13',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-04-18T17:55:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '38',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Sedie rotte',
    description: 'Tre sedie di plastica rotte lasciate in un parco.',
    address: 'Via Mendel 22',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2025-03-31T08:30:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '39',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Tubazioni metalliche',
    description: 'Tubi metallici abbandonati dopo lavori idraulici.',
    address: 'Via Planck 16',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-03-30T14:15:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '40',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Radio vecchia',
    description: 'Radio vintage abbandonata vicino a una fermata.',
    address: 'Via Bohr 9',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-03-29T11:45:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '41',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Libreria dismessa',
    description: 'Libreria in legno abbandonata davanti a una scuola.',
    address: 'Via Heisenberg 7',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-03-28T16:20:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '42',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Piastrelle ceramiche',
    description: 'Scatole di piastrelle ceramiche rotte.',
    address: 'Via Schrödinger 11',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2025-03-27T09:35:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '43',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Telefono fisso',
    description: 'Vecchio telefono fisso lasciato in strada.',
    address: 'Via Fermi 18',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-03-26T12:50:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '44',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Materasso singolo',
    description: 'Materasso singolo abbandonato in un vicolo.',
    address: 'Via Rutherford 5',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-03-25T15:10:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '45',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Secchi di vernice',
    description: 'Secchi di vernice vuoti lasciati dopo imbiancatura.',
    address: 'Via Pauli 23',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-03-24T10:25:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '46',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Fotocopiatrice',
    description: 'Fotocopiatrice rotta abbandonata in un ufficio.',
    address: 'Via Dirac 15',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2025-03-23T13:40:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '47',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Comodino vecchio',
    description: 'Comodino in legno lasciato sul marciapiede.',
    address: 'Via Hawking 8',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-03-22T17:15:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '48',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Lastre di vetro',
    description: 'Lastre di vetro rotte da finestra.',
    address: 'Via Planck 20',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-03-21T08:55:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '49',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Lettore DVD',
    description: 'Lettore DVD rotto abbandonato in un parco.',
    address: 'Via Maxwell 12',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-03-20T14:30:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '50',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Cestino rotto',
    description: 'Cestino della spazzatura danneggiato.',
    address: 'Via Faraday 17',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2025-03-19T11:45:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '51',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Isolante termico',
    description: 'Pannelli isolanti abbandonati dopo lavori.',
    address: 'Via Ampère 6',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-03-18T16:20:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '52',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Calcolatrice rotta',
    description: 'Calcolatrice elettronica danneggiata.',
    address: 'Via Ohm 24',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-03-17T09:10:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '53',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Panca da giardino',
    description: 'Panca in ferro arrugginita abbandonata.',
    address: 'Via Hertz 13',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-03-16T12:35:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '54',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Cartongesso rotto',
    description: 'Pezzi di cartongesso dopo demolizione.',
    address: 'Via Gauss 10',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2025-03-15T15:50:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '55',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Stereo portatile',
    description: 'Stereo portatile rotto lasciato in piazza.',
    address: 'Via Coulomb 21',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-03-14T10:15:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '56',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Specchio grande',
    description: 'Specchio rotto da bagno abbandonato.',
    address: 'Via Joule 7',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-03-13T13:25:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '57',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Cavi elettrici',
    description: 'Bobina di cavi elettrici abbandonati.',
    address: 'Via Watt 14',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-03-12T17:40:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '58',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Console giochi',
    description: 'Console per videogiochi rotta.',
    address: 'Via Pascal 19',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2025-03-11T08:50:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '59',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Carrello spesa',
    description: 'Carrello della spesa abbandonato in strada.',
    address: 'Via Kelvin 3',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-03-10T14:05:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '60',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Sanitari rotti',
    description: 'Water e bidet rotti dopo ristrutturazione.',
    address: 'Via Bernoulli 26',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-03-09T11:30:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '61',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Macchina caffè',
    description: 'Macchina per caffè espresso rotta.',
    address: 'Via Torricelli 9',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-02-28T16:45:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '62',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Frigorifero piccolo',
    description: 'Frigobar abbandonato vicino a un bar.',
    address: 'Via Galileo 15',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2025-02-27T09:20:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '63',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Tegole rotte',
    description: 'Tegole del tetto cadute dopo temporale.',
    address: 'Via Archimede 22',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-02-26T12:10:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '64',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Campanello rotto',
    description: 'Citofono elettronico danneggiato.',
    address: 'Via Euclide 8',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-02-25T15:35:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '65',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Bicicletta rotta',
    description: 'Bicicletta danneggiata senza ruote.',
    address: 'Via Pitagora 11',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-02-24T10:25:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '66',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Grondaie vecchie',
    description: 'Pezzi di grondaia metallica arrugginita.',
    address: 'Via Talete 17',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2025-02-23T13:40:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '67',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Router wifi',
    description: 'Router internet rotto abbandonato.',
    address: 'Via Apollonio 4',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-02-22T17:55:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '68',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Sedia a rotelle',
    description: 'Sedia a rotelle danneggiata.',
    address: 'Via Eratostene 20',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-02-21T08:15:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '69',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Pannelli legno',
    description: 'Pannelli di compensato dopo demolizione.',
    address: 'Via Ipparco 13',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-02-20T14:50:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '70',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Tablet rotto',
    description: 'Tablet con schermo frantumato.',
    address: 'Via Aristarco 6',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2025-02-19T11:25:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '71',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Cassettiera usata',
    description: 'Cassettiera in legno con cassetti rotti.',
    address: 'Via Anassagora 19',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-02-18T16:10:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '72',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Intonaco caduto',
    description: 'Pezzi di intonaco caduti dalla facciata.',
    address: 'Via Democrito 25',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-02-17T09:35:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '73',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Decoder TV',
    description: 'Decoder digitale terrestre rotto.',
    address: 'Via Empedocle 12',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-02-16T12:45:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '74',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Mensole rotte',
    description: 'Mensole di legno cadute dal muro.',
    address: 'Via Zenone 7',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2025-02-15T15:20:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '75',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Blocchi cemento',
    description: 'Blocchi di cemento armato dopo demolizione.',
    address: 'Via Parmenide 18',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-02-14T10:55:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '76',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Cuffie rotte',
    description: 'Cuffie stereo danneggiate.',
    address: 'Via Eraclito 23',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-02-13T13:30:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '77',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Ombrellone rotto',
    description: 'Ombrellone da giardino strappato dal vento.',
    address: 'Via Leucippo 9',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-02-12T17:15:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '78',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Polvere amianto',
    description: 'Residui di materiale contenente amianto.',
    address: 'Via Melisso 14',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2025-02-11T08:40:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '79',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Hard disk esterno',
    description: 'Disco rigido esterno danneggiato.',
    address: 'Via Gorgia 21',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-02-10T14:25:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '80',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Passeggino rotto',
    description: 'Passeggino per bambini con ruote danneggiate.',
    address: 'Via Protagora 5',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-02-09T11:50:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '81',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Finestre vecchie',
    description: 'Infissi in alluminio sostituiti.',
    address: 'Via Ippia 16',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-01-31T16:35:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '82',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Mouse e tastiera',
    description: 'Periferiche computer danneggiate.',
    address: 'Via Prodico 22',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2025-01-30T09:15:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '83',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Tenda da sole',
    description: 'Tenda da sole strappata dal maltempo.',
    address: 'Via Antifonte 8',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-01-29T12:40:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '84',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Rivestimenti bagno',
    description: 'Piastrelle vecchie del bagno rimosse.',
    address: 'Via Liside 11',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-01-28T15:55:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '85',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Lampada da terra',
    description: 'Lampada da terra con base rotta.',
    address: 'Via Crizia 17',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-01-27T10:20:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '86',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Banco da lavoro',
    description: 'Banco da lavoro in metallo arrugginito.',
    address: 'Via Callicle 24',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2025-01-26T13:45:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '87',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Coppi danneggiati',
    description: 'Coppi del tetto caduti durante i lavori.',
    address: 'Via Trasimaco 6',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-01-25T17:10:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '88',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Sveglia digitale',
    description: 'Radiosveglia con display rotto.',
    address: 'Via Alcidamante 13',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-01-24T08:25:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '89',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Appendiabiti rotto',
    description: 'Appendiabiti in legno con ganci spezzati.',
    address: 'Via Isocrate 19',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-01-23T14:50:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '90',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Massetto rovinato',
    description: 'Pezzi di massetto demolito.',
    address: 'Via Lisia 25',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2025-01-22T11:15:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '91',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Smartphone rotto',
    description: 'Telefono cellulare con schermo frantumato.',
    address: 'Via Eschine 7',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-01-21T16:30:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '92',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Sgabello rotto',
    description: 'Sgabello da bar con gambe spezzate.',
    address: 'Via Dinarco 12',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-01-20T09:45:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '93',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Cordoli stradali',
    description: 'Cordoli in cemento rimossi dalla strada.',
    address: 'Via Iperide 18',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-01-19T12:20:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '94',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Caricabatterie rotto',
    description: 'Caricabatterie per cellulare danneggiato.',
    address: 'Via Demostene 23',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2025-01-18T15:35:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '95',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Tappeto vecchio',
    description: "Tappeto persiano rovinato dall'umidità.",
    address: 'Via Licurgo 9',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2025-01-17T10:50:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '96',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Mattoni forati',
    description: 'Mattoni forati da costruzione abbandonati.',
    address: 'Via Andocide 15',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2025-01-16T13:15:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '97',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Altoparlanti rotti',
    description: 'Casse audio con coni danneggiati.',
    address: 'Via Antifonte 21',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2025-01-15T17:25:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '98',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Vaso da fiori',
    description: 'Vaso in terracotta rotto caduto dal balcone.',
    address: 'Via Crizia 4',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2024-12-31T08:40:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '99',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Guaine impermeabili',
    description: 'Rotoli di guaina bituminosa usurata.',
    address: 'Via Prodico 26',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2024-12-30T14:55:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '100',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Webcam rotta',
    description: 'Webcam per computer con lente danneggiata.',
    address: 'Via Ippia 11',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2024-12-29T11:10:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '101',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Cancelletto rotto',
    description: 'Cancelletto da giardino con cerniere rotte.',
    address: 'Via Liside 16',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2024-12-28T16:20:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '102',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Piastrelle bagno',
    description: 'Rivestimenti ceramici rimossi da bagno.',
    address: 'Via Callicle 8',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2024-12-27T09:35:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '103',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Mixer audio',
    description: 'Console mixer per audio con potenziometri rotti.',
    address: 'Via Trasimaco 22',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2024-12-26T12:45:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '104',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Fioriera rotta',
    description: 'Fioriera in cemento con crepe profonde.',
    address: 'Via Alcidamante 19',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2024-12-25T15:50:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '105',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Cemento armato',
    description: 'Blocchi di cemento armato da demolizione.',
    address: 'Via Isocrate 3',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2024-12-24T10:25:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '106',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Telecomando TV',
    description: 'Telecomando con tasti non funzionanti.',
    address: 'Via Lisia 14',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2024-12-23T13:40:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '107',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Poltroncina ufficio',
    description: 'Sedia da ufficio con ruote rotte.',
    address: 'Via Eschine 27',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2024-12-22T17:15:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '108',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Scossaline metalliche',
    description: 'Scossaline del tetto arrugginite.',
    address: 'Via Dinarco 20',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2024-12-21T08:30:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '109',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Joystick console',
    description: 'Controller per videogiochi con analogici rotti.',
    address: 'Via Iperide 5',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2024-12-20T14:05:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '110',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Contenitore plastica',
    description: 'Contenitore per raccolta differenziata rotto.',
    address: 'Via Demostene 12',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2024-12-19T11:20:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '111',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Pali recinzione',
    description: 'Pali in ferro per recinzione arrugginiti.',
    address: 'Via Licurgo 25',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2024-12-18T16:45:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '112',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Modem internet',
    description: 'Modem ADSL con alimentatore rotto.',
    address: 'Via Andocide 7',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2024-12-17T09:55:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '113',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Stendibiancheria',
    description: 'Stendibiancheria in alluminio piegato dal vento.',
    address: 'Via Antifonte 18',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2024-12-16T12:30:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '114',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Blocchi tufo',
    description: 'Blocchi di tufo da costruzione abbandonati.',
    address: 'Via Crizia 21',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2024-12-15T15:15:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '115',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Chiavetta USB',
    description: 'Dispositivo USB danneggiato.',
    address: 'Via Prodico 13',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2024-12-14T10:40:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '116',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Tavola da stiro',
    description: 'Tavola da stiro con gambe instabili.',
    address: 'Via Ippia 24',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2024-12-13T13:25:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '117',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Griglia ventilazione',
    description: 'Griglie di ventilazione ossidate.',
    address: 'Via Liside 10',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2024-12-12T17:50:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '118',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Cavo ethernet',
    description: 'Cavo di rete danneggiato.',
    address: 'Via Callicle 16',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2024-12-11T08:15:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '119',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Bacinella rotta',
    description: 'Bacinella in plastica con fondo bucato.',
    address: 'Via Trasimaco 9',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2024-12-10T14:35:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '120',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Controtelaio finestra',
    description: 'Controtelaio in alluminio dopo sostituzione.',
    address: 'Via Alcidamante 23',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2024-12-09T11:50:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '121',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Powerbank rotto',
    description: 'Batteria portatile che non si ricarica.',
    address: 'Via Isocrate 15',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2024-12-08T16:25:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '122',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Cassapanca legno',
    description: 'Cassapanca antica con coperchio rotto.',
    address: 'Via Lisia 6',
    location: {
      latitude: 45.4672,
      longitude: 9.1967,
    },
    date: new Date('2024-12-07T09:10:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '123',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Calcestruzzo rotto',
    description: 'Pezzi di calcestruzzo da demolizione stradale.',
    address: 'Via Eschine 17',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2024-12-06T12:40:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '124',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Videocamera rotta',
    description: 'Videocamera digitale con obiettivo bloccato.',
    address: 'Via Dinarco 28',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2024-12-05T15:55:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '125',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Bidone spazzatura',
    description: 'Bidone della spazzatura con ruote rotte.',
    address: 'Via Iperide 12',
    location: {
      latitude: 45.466,
      longitude: 9.1905,
    },
    date: new Date('2024-12-04T10:20:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '126',
    images: [BuildingMaterialsDisposalImage, ElectricalWasteDisposalImage],
    title: 'Rete metallica',
    description: 'Rotoli di rete metallica arrugginita.',
    address: 'Via Demostene 19',
    location: {
      latitude: 45.4672,
      longitude: 9.1834,
    },
    date: new Date('2024-12-03T13:45:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '127',
    images: [ElectricalWasteDisposalImage, BulkyWasteDisposalImage],
    title: 'Interruttore rotto',
    description: 'Interruttore elettrico danneggiato.',
    address: 'Via Licurgo 4',
    location: {
      latitude: 45.4668,
      longitude: 9.1822,
    },
    date: new Date('2024-12-02T17:30:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '128',
    images: [BulkyWasteDisposalImage, ElectricalWasteDisposalImage],
    title: 'Scala a pioli',
    description: 'Scala in alluminio con gradini piegati.',
    address: 'Via Andocide 26',
    location: {
      latitude: 45.4665,
      longitude: 9.1901,
    },
    date: new Date('2024-12-01T08:45:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
]

export default REPORTS
