import {
  BulkyWasteDisposalImage,
  BuildingMaterialsDisposalImage,
  ElectricalWasteDisposalImage,
} from '@assets';

import { Report, StatusOption, PriorityOption } from '@types';

const REPORTS: Report[] = [
  {
    id: '1',
    image: BulkyWasteDisposalImage,
    title: 'Rifiuti ingombranti',
    description: 'Abbandono di rifiuti ingombranti sul marciapiede. Necessaria rimozione urgente.',
    address: 'Via Torino 45',
    date: new Date('2025-05-26T14:30:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '2',
    image: BuildingMaterialsDisposalImage,
    title: 'Materiali edili',
    description: 'Materiali edili abbandonati dopo lavori di ristrutturazione. Occupano parte della strada.',
    address: 'Piazza Duomo 12',
    date: new Date('2025-05-25T14:30:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Medium,
  },
  {
    id: '3',
    image: ElectricalWasteDisposalImage,
    title: 'Rifiuti elettrici',
    description: 'Elettrodomestici e apparecchiature elettroniche abbandonate. Potenziale rischio ambientale.',
    address: 'Via Montenapoleone 8',
    date: new Date('2025-05-23T14:30:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Low,
  },
  {
    id: '4',
    image: BulkyWasteDisposalImage,
    title: 'Mobili abbandonati',
    description: 'Divano e altri mobili abbandonati nel parco pubblico. Creano ostacolo al passaggio.',
    address: 'Via Garibaldi 78',
    date: new Date('2025-05-22T10:15:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.Medium,
  },
  {
    id: '5',
    image: ElectricalWasteDisposalImage,
    title: 'Computer e monitor',
    description: 'Diversi computer e monitor abbandonati vicino ai cassonetti. Necessaria raccolta speciale.',
    address: 'Corso Vittorio Emanuele 34',
    date: new Date('2025-05-21T16:45:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Low,
  },
  {
    id: '6',
    image: BuildingMaterialsDisposalImage,
    title: 'Calcinacci e mattoni',
    description: 'Cumulo di calcinacci e mattoni abbandonati dopo demolizione. Occupano il marciapiede.',
    address: 'Via Dante 56',
    date: new Date('2025-05-20T09:30:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '7',
    image: BulkyWasteDisposalImage,
    title: 'Elettrodomestici grandi',
    description: 'Frigorifero e lavatrice abbandonati in strada. Bloccano parzialmente il passaggio pedonale.',
    address: 'Via Manzoni 23',
    date: new Date('2025-05-19T14:20:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.High,
  },
  {
    id: '8',
    image: ElectricalWasteDisposalImage,
    title: 'Batterie e pile',
    description: 'Accumulo di batterie e pile usate abbandonate. Rischio di contaminazione ambientale.',
    address: 'Piazza Repubblica 5',
    date: new Date('2025-05-18T11:10:00'),
    status: StatusOption.Working,
    priority: PriorityOption.High,
  },
  {
    id: '9',
    image: BuildingMaterialsDisposalImage,
    title: 'Vernici e solventi',
    description: 'Barattoli di vernice e solventi abbandonati. Rischio di sversamento e inquinamento.',
    address: 'Via Leopardi 67',
    date: new Date('2025-05-17T15:50:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.High,
  },
  {
    id: '10',
    image: BulkyWasteDisposalImage,
    title: 'Materassi vecchi',
    description: 'Tre materassi vecchi abbandonati sul ciglio della strada. Necessaria rimozione.',
    address: 'Corso Magenta 89',
    date: new Date('2025-05-16T13:25:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.Low,
  },
  {
    id: '11',
    image: ElectricalWasteDisposalImage,
    title: 'Cavi elettrici',
    description: 'Matassa di cavi elettrici abbandonati. Potenziale pericolo per i passanti.',
    address: 'Via Brera 12',
    date: new Date('2025-05-15T10:40:00'),
    status: StatusOption.Working,
    priority: PriorityOption.Medium,
  },
  {
    id: '12',
    image: BuildingMaterialsDisposalImage,
    title: 'Piastrelle rotte',
    description: 'Cumulo di piastrelle rotte abbandonate dopo ristrutturazione. Rischio di ferimento.',
    address: 'Via Solferino 45',
    date: new Date('2025-05-14T17:15:00'),
    status: StatusOption.Completed,
    priority: PriorityOption.Medium,
  },
  {
    id: '13',
    image: BulkyWasteDisposalImage,
    title: 'Pneumatici usati',
    description: 'Diversi pneumatici usati abbandonati. Rischio di ristagno acqua e proliferazione zanzare.',
    address: 'Viale Certosa 78',
    date: new Date('2025-05-13T09:05:00'),
    status: StatusOption.Pending,
    priority: PriorityOption.Medium,
  },
];

export default REPORTS;
